services:
  # Reservations application container
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  # Auth application container
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  # Mongodb database service
  mongo:
    image: mongo